name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Tests ✅
        run: npm test

      - name: Deploy to EC2 🚀
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/my-test-app
            git pull origin main
            npm install
            npm run build || echo "No build step"
            pm2 restart my-test-app || pm2 start index.js --name my-test-app
            echo "✅ Deployment completed"

