name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "47.129.39.89"            # Make sure this is in quotes
          username: "ubuntu"
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            cd /home/ubuntu/my-test-app
            git pull origin main
            pm2 restart my-test-app || pm2 start index.js --name my-test-app

