name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > Myansiblekey.pem
          chmod 600 Myansiblekey.pem

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key_path: ./Myansiblekey.pem
          port: 22
          script: |
            cd /home/ubuntu/my-test-app
            git pull origin main
            pm2 restart my-test-app || pm2 start index.js --name my-test-app

