name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Decode SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 47.129.39.89
        username: ubuntu
        key: ./private_key.pem
        port: 22
        script: |
          cd /home/ubuntu/my-test-app
          git pull origin main
          pm2 restart my-test-app || pm2 start index.js --name my-test-app

